### ISSUE TITLE
Congratulations Chema! Beautiful Work!!!

### ISSUE THREAD

**Issue by inglesuniversal** [ChemaAlfonso/neumorph.scss#1]
Love every single detail.

Do you welcome ideas for more components?

**Comment by ChemaAlfonso** [comment]
Hi Hugo, thank you so much!

Of course, all improvements are welcome, fell free to make them :)

**Comment by ChemaAlfonso** [comment]
Hi Hugo, Thank you so much. Of course, all improvement ideas are welcome, fell free to do pull requests 😊  De: Hugo BarbosaEnviado: sábado, 21 de marzo de 2020 14:31Para: ChemaAlfonso/neumorph.scssCC: SubscribedAsunto: [ChemaAlfonso/neumorph.scss] Congratulations Chema! Beautiful Work!!! (#1) Love every single detail.Do you welcome ideas for more components?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
